{errorType:Error,errorMessage:Client has already been connected. You cannot reuse a client.,trace:[Error: Client has already been connected. You cannot reuse a client.,    at Client._connect (/var/task/node_modules/pg/lib/client.js:91:17),    at /var/task/node_modules/pg/lib/client.js:310:10,    at new Promise (<anonymous>),    at Client.connect (/var/task/node_modules/pg/lib/client.js:309:10),    at runQuerry (/var/task/index.js:21:16),    at Runtime.exports.handler (/var/task/index.js:16:10),    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)]}
